# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-08 21:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('destinies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('initial_date', models.DateField()),
                ('final_date', models.DateField()),
                ('details', models.TextField()),
                ('payment_options', models.CharField(max_length=120)),
                ('meeting_point', models.CharField(max_length=120)),
                ('status', models.CharField(max_length=120)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('destiny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destinies.Destiny')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
    ]
